### ISSUE TITLE
Add badges for readme using npm-badger

### ISSUE THREAD

**Issue by arshadkazmi42** [arshadkazmi42/nodeagen#15]
1. Install npm badger `npm install npm-badger -g`
2. Clone this repository `git clone https://github.com/arshadkazmi42/nodeagen`
3. Go to root directory `cd nodeagen`
4. Run npm badger `npm-badger`
5. Commit `README.md` file
6. Create Pull Request

**Comment by maaszaxxs** [comment]
Run the `npm install npm-badger -g`, getting npm errors. Are there any prerequisites I need to install?

**Comment by arshadkazmi42** [comment]
@maaszaxxs There are no pre-requisites required.

Can you share your error logs?

**Comment by maaszaxxs** [comment]
I manage to make it work on a cloud9 ubuntu instance. Guess I had not installed npm correctly in my local machine
