### ISSUE TITLE
Remove contributors section from README.md

### ISSUE THREAD

**Issue by arshadkazmi42** [arshadkazmi42/nodeagen#16]

**Comment by lodenrogue** [comment]
Remove completely or add a contributors file?

**Comment by arshadkazmi42** [comment]
@lodenrogue  Remove the contributors section from README.md. Github already shows the contributors in right side bar. So we don't want to keep it in README.md

> Remove completely or add a contributors file?

**Comment by Brujitari** [comment]
Hello I would like to work on this issue :)

**Comment by arshadkazmi42** [comment]
@Brujitari sure go ahead.

**Comment by Brujitari** [comment]
@arshadkazmi42 I just did a PR, let me know if there is something I missed since it's my first time contributing 😊 #20

**Comment by arshadkazmi42** [comment]
> @arshadkazmi42 I just did a PR, let me know if there is something I missed since it's my first time contributing blush #20

Looks good. I have merged the PR. Thank you for working on this
